### ISSUE TITLE
Query iterators

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#106]
DAS query API should optionally return iterators rather than lists with results. The point here is to reduce response time to a minimal specially when the calls involve remote calls. These iterators need to be integrated with the cache system and should be implemented all the way down in the stack of requests from DAS until the data structure actually storing atoms (AtomDB adapters).

**Comment by marcocapozzoli** [comment]
This Issue was resolved by #138 #139 #145 #147
