### ISSUE TITLE
How to launch your own das server?

### ISSUE THREAD

**Issue by CICS-Oleg** [singnet/das-query-engine#111]
Could you provide some resources on how to launch your own endpoint with DistributedAtomSpace? All attempts to create it with redis and mongo lead to hanging up. Ports and IPs are valid, databases are avaliable. What could gone wrong? Thank you in advance.

**Comment by andre-senna** [comment]
This is being implemented by https://github.com/singnet/das-query-engine/issues/107
Duplicates #107
