### ISSUE TITLE
Atom deletion

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#113]

**Comment by marcocapozzoli** [comment]
O que precisa ser Feito:


1) Adicionar método público na classe DistributedAtomSpace com o seguinte contrato:

    `def remove_atom(self, handle: str, **kwargs) -> bool: ...`
    
    obs: no kwargs pode ser passado uma parametro para remover o Atom apenas Remoto ou Local e Remoto (Default: Local e Remoto)
    `'scope' = 'remote_only'` ou `'scope' = 'local_and_remote'` (default)
    
    obs: Levanta uma Exception caso o Atom não exista
    
2) Esse método deve repassar a chamada para o query_engine remoto (RemoteQueryEngine)

```
    def remove_atom(self, handle: str,  kwargs) -> bool:
        scope = kwargs.get('scope', 'local_and_remote')
        try:
            if scope == 'remote_only':
                self.remote_das.remove_atom(handle, **kwargs)
            elif query_scope == 'local_and_remote':
                self.local_query_engine.remove_atom(handle, **kwargs)
                self.remote_das.remove_atom(handle, **kwargs)
            return True
         except Exception:
            return False
```

3) Escrever esse método na classe LocalQueryEngine

4) Escrever esse método na classe FunctionsClient

5) Criar testes

== Alterações no AtomDB ==


1) Escrever o método remove_atom() na classe abstrata `AtomDB`

```
    @abstractmethod
    def remove_atom(self, handle: str, **kwargs) -> bool: ...
```

2) Escrever o método nas classes concretas `InMemoryDB` e `RedisMongoDB`

2.1) No InMemoryDB:
    a) Caso seja um Link remover nas hashMaps: `atom_type`, `link`, `node`, `incoming_set`, `outgoing_set`, `patterns` e `templates`
    b) Caso sena um Node remover nas hashMaps: `atom_type` e `node`

2.2) No RedisMongoDB
    a) Caso seja um Link remover
        - no MongoDB o document nas collections: `atom_types`, `links_1`, `links_2`, `links_n` e `nodes`
        - no Redis os dados em: `names`, `incomming_set`, `outgoing_set`, `patterns` e `templates`
    b) Caso sena um Node remover
        - no MongoDB o document nas collections: `atom_types` e `nodes`
        - no Redis os dados em: `names`
        
3) Criar testes
        
==  Alterações no ServlessFunction ==

1) Adiconar o método remove_atom() na classe `Actions`
2) Adicionar um type na classe `ActionType`
3) Acicionar no dispatcher da classe `ActionMapper`
4) Criar uma classe de validação no arquivo `validators>actions.py`
5) criar testes

**Comment by marcocapozzoli** [comment]
Children's issues solved
singnet/das-atom-db/issues/84
singnet/das-atom-db/issues/85
