### ISSUE TITLE
Unexpected behavior of query engine

### ISSUE THREAD

**Issue by CICS-Oleg** [singnet/das-query-engine#120]
In my previous tests and experimnets I overlooked this type of problem with das `query` method:
the code below 

```
from hyperon_das import DistributedAtomSpace
from hyperon_das.constants import QueryOutputFormat

das = DistributedAtomSpace()

das.add_link({
    "type": "Expression",
    "targets": [
        {"type": "Symbol", "name": "Test"},
        {
            "type": "Expression",
            "targets": [
                {"type": "Symbol", "name": "Test"},
                {"type": "Symbol", "name": "2"}
            ]
        }
    ]
})

query_params = {
    "toplevel_only": False,
    "return_type": QueryOutputFormat.ATOM_INFO,
    'query_scope': 'local_only'
}

q4 = {
    'atom_type': 'link',
    'type': 'Expression',
    'targets': [
        {'atom_type': 'variable', 'name': '$v1'},
        {
            'atom_type': 'link', 'type': 'Expression', 'targets': [
                {'atom_type': 'node', 'type': 'Symbol', 'name': 'Test'},
                {'atom_type': 'node', 'type': 'Symbol', 'name': '2'}
            ]
         }
    ]
}

answer = das.query(q4, query_params)
```
outputs this

`[{'handle': 'dbcf1c7b610a5adea335bf08f6509978', 'type': 'Expression', 'targets': [{'handle': '963d66edfb77236054125e3eb866c8b5', 'type': 'Symbol', 'name': 'Test'}, {'handle': '233d9a6da7d49d4164d863569e9ab7b6', 'type': 'Expression', 'targets': [{'handle': '963d66edfb77236054125e3eb866c8b5', 'type': 'Symbol', 'name': 'Test'}, {'handle': '9f27a331633c8bc3c49435ffabb9110e', 'type': 'Symbol', 'name': '2'}]}]}]`

But we're expecting something like that:

`[{'handle': '963d66edfb77236054125e3eb866c8b5', 'type': 'Symbol', 'name': 'Test'}]`

i.e. having `(Test (Test 2))` inside a database and `($v1 (Test 2))` as a query we experct das to retrieve `$v1 <- Test`, but not `$v1 <- (Test (Test 2))`

**Comment by Necr0x0Der** [comment]
I'd add that it worked correctly in some previous versions.
