### ISSUE TITLE
DasAPI is not available

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/das-query-engine#17]
After recent changes, `DasAPI` is not available.
Please, provide the right way to replace former code:
```
from hyperon_das import DasAPI
das = DasAPI('hash_table')
```

**Comment by marcocapozzoli** [comment]
Sorry about that, we made some changes.

Now, you must call the API like this:
```
from hyperon_das import DistributedAtomSpace
api = DistributedAtomSpace('ram_only')
```

See this link for more details:
https://github.com/singnet/das-query-engine#in-memory

**Comment by Necr0x0Der** [comment]
@CICS-Oleg, could you please fix dasgate in Hyperon and close this issue of this.

**Comment by CICS-Oleg** [comment]
@Necr0x0Der Done
