### ISSUE TITLE
Check if `clear_database()` in redis_mongo is deleting custom indexes

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#227]
Custom indexes are supposed to be deleted when this method is called.

**Comment by marcocapozzoli** [comment]
Custom indexes are stored in MongoDB in a collection called Atoms and this collection (and all of them) are deleted during the .clear_database() process


![Image](https://github.com/user-attachments/assets/93c0e50b-621f-41a3-b28b-cd1727bada3e)
