### ISSUE TITLE
Review error messages and raising conditions

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#31]
Goals:

* Review error messages to fix English mistakes and to remove ambiguities
* Make sure all raised errors are logged
* Standardize the way errors are raised and catched considering two use cases scenarios
    * DAS server running redis_mongo AtomDB - error logging and raising should consider the fact that DAS Server is called by a FaaS server
    * Clients using a remote DAS server or a ram_only DAS - error logging and raising should consider that clients are running DAS queries either as a python program running our library or inside MeTTa interpreter.

* Query-engine
* AtomDB
* Functions

**Comment by Pedrobc89** [comment]
https://github.com/singnet/das-query-engine
https://github.com/singnet/das-serverless-functions
https://github.com/singnet/das-atom-db
