### ISSUE TITLE
Refactor Makefile and parametrization of lint commands

### ISSUE THREAD

**Issue by marcocapozzoli** [singnet/das-query-engine#44]
* List all the tools and all the points each tool will report/fix with any suggested parameters for each one. The idea is to present this list in our internal call to discuss with all the team and have an agreement on what should/shouldn't be reported/fixed as well as the parameters values.
* Write a `pyproject.toml` according to this discussion results
* Change the Makefile (query engine and atom db) to have the same commands:
    * `unit-tests` - run unit tests without coverage check
    * `unit-tests-coverage` - run unit tests with coverage check
    * `integration-tests`
    * `pre-commit` - run unit tests with coverage and all lint commands

The list of the first point is supposed to be a comprehensive list like:

* Tool 1
    * Limit line width to 79 characters
    * Ceck type hint in functions and methods declaration
    * etc
* Tool 2
    * etc
* etc

Instead of something like: `--multi-line=3 --trailing-comma --force-grid-wrap=0`

**Comment by andre-senna** [comment]
We may discuss this point but I think we need to remove methods sorting by name. I strongly believe that developers have a much better feeling of what methods should be placed together than any automatic sort criteria. In addition to this, depending on the class we are talking about, methods should be grouped differently. 

For instance, a public class (meaning a class that's heavily used by users) like DAS should have piublic API methods grouped together and subgroups of related methods like get_atom(), get_link() and get_node() should be put together and any private methods should be put elsewhere. However, a heavy-algorithmic and obscure classes (not used by (most) users) may have some private methods (sometimes used only once inside the class) grouped together with the public methods that calls it. My point is: there is no way to define a generic set of criteria to sort methods. I think we should rely on developer's judgement.

**Comment by marcocapozzoli** [comment]
Tool: isort
Target: sort imports
Parameters:
--multi-line=3 -> Specifies the maximum number of imports that can be on a single line. In this case if there are more than 3 imports in a single line, they will be split into multiple lines.
--trailing-comma -> Enforces adding a trailing comma to the last import If these imports are enclosed in parentheses.
--force-grid-wrap=0 -> Determines how imports are wrapped when they exceed the maximum line length. In this case, it will try to fit as many imports as possible on a single line without exceeding the specified line width (parameter e).
--use-parentheses -> Enforces wrapping all imports in parentheses.
--line-width=100 -> Sets the maximum line length.

Tool: black
Target: code style
Parameters:
--line-length 100 -> Specifies the maximum number of imports that can be on a single line. In this case if there are more than 3 imports in a single line, they will be split into multiple lines.
-t py37 -> Enforces adding a trailing comma to the last import If these imports are enclosed in parentheses.
--skip-string-normalization -> Determines how imports are wrapped when they exceed the maximum line length. In this case, it will try to fit as many imports as possible on a single line without exceeding the specified line width (parameter e).

Tool: flake8
Target: linting, style checking (use PEP8). Help enforce coding standards and identify potential issue
Parameters:
--show-source -> show source code lines in the output
