### ISSUE TITLE
Run `pre-commit` command automatically when a PR is submitted

### ISSUE THREAD

**Issue by andre-senna** [singnet/das-query-engine#45]
Depends on https://github.com/singnet/das-query-engine/issues/44
Make it for AtomDB as well.

**Comment by andre-senna** [comment]
Depends on https://github.com/singnet/das-query-engine/issues/44

**Comment by levisingularity** [comment]
PRs: https://github.com/singnet/das-atom-db/pull/74 & https://github.com/singnet/das-query-engine/pull/95 & https://github.com/singnet/das-servless-functions/pull/51 & https://github.com/singnet/das-servless-functions/pull/51
