### ISSUE TITLE
Need to distinguish nodes and links by handle

### ISSUE THREAD

**Issue by Necr0x0Der** [singnet/das-query-engine#7]
`query` or `matched` results contain handles. We need to convert them into expressions. To do this, we need to distinguish nodes and links in order to call `get_node_name` or `get_link_targets`. Is there a better way than just catching an exception?

**Comment by Necr0x0Der** [comment]
Sorry, but it is not solved. While the return type is changed, the result is still a string, because of the code:
https://github.com/singnet/das-query-engine/blob/38079bb9d1c461848dbe2153224cd9091c796194/hyperon_das/api.py#L586C37-L586C37
It always of `str` type. Also, the issue is about distinguishing nodes and links, but the output now (even for `ATOM_INFO`) is something like:
```
[{'v1': {'type': 'Symbol', 'name': 'Test'}}]
```
That is, it doesn't include information whether it is node or link.

**Comment by andre-senna** [comment]
Actually it does, although indirectly (Nodes always have `name` and no `targets` while links always have `targets` and not `name`).

But I see no problem in including explicit boolean fields `is_node` and `is_link`. 

@marcocapozzoli   I think it'd be easy to add those. If so, please commit this change.

**Comment by Necr0x0Der** [comment]
What's about an option to remove the conversion of the result to `str`? Maybe, it should be done for some output formats, but not for `ATOM_INFO`?

**Comment by Necr0x0Der** [comment]
> Actually it does, although indirectly 

Well, I'm ok with distinguishing nodes and links implicitly, although it is not a perfect approach.

**Comment by Necr0x0Der** [comment]
In any case, as far as I can see, `get_atom` method with `ATOM_INFO` can be used to retrieve information about the atom using its handle, and it seems to be sufficient, so, maybe, no need to modify `query`, although I'm still not sure if using `PatternMatchingAnswer` is a supposed method for calling queries from Python, while `query` is more for network calls.
